### ISSUE TITLE
Can't connect to Wallabag Self-Host Service, URL error

### ISSUE THREAD

**Issue by starsareintherose** [wallabag/android-app#1137]
# Issue details
Can't connect to Wallabag Self-Host Service, URL error
### Duplicate?
Have you searched the issues of this repository if your issue is already known? yes/no
yes, but I can't solve based on them.
### Actual behaviour
- Tell us what happens
```
curl -I https://read.malacology.net
HTTP/1.1 302 Found
Server: nginx/1.14.0 (Ubuntu)
Date: Thu, 04 Mar 2021 05:53:40 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: PHPSESSID=6d5b8a61927e317de1f72f67f9533c73; path=/; HttpOnly
Cache-Control: max-age=0, must-revalidate, private
Location: http://read.malacology.net/login
pragma: no-cache
Expires: Thu, 04 Mar 2021 05:53:40 GMT
```
# Steps to reproduce the issue
1. docker-compose up -d
```
version: '2'
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=guoyiwang123
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=guoyiwang123
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=dockerwallabag
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=starsareintherose@outlook.com
      - SYMFONY__ENV__DOMAIN_NAME=https://read.malacology.net
      - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
    ports:
      - "808:80"
    volumes:
      - /opt/wallabag/images:/var/www/html/wallabag-dcoker/web/assets/images
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
    volumes:
      - /opt/wallabag/data:/var/lib/mysql
  redis:
    image: redis:alpine
```
2. set the nginx proxy and SSL
```
server {
    listen 443;
    server_name read.malacology.net;
    ssl_certificate /etc/ssl/read/1_read.malacology.net_bundle.crt;
    ssl_certificate_key /etc/ssl/read/2_read.malacology.net.key;
    ssl on;
    ssl_session_cache builtin:1000 shared:SSL:10m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;
    access_log /var/log/nginx/access.log;
    
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://120.77.245.50:808;
        proxy_read_timeout 90;
        proxy_redirect http://120.77.245.50:808 https://read.malacology.net;
    }
}
```
3. login and change the password

# Environment details
- **wallabag app version**: Latest on Google Play
- **wallabag app installation source** (e.g. Gplay, F-Droid, manual): Google Play
- **Android OS version**: MIUI
- **Android ROM** (e.g. stock, LineageOS, SlimRom,…): unknown
- **Android hardware**: unknown
- **wallabag server version**: latest on docker
- **Do you have Two-Factor-Authentication enabled?**: no
